services:
  backend:
    build: ./backend-api
    ports:
      - "8080:8080"
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/serviceAccountKey.json
    env_file:
      - .env
  tests:
    build: ./backend-api
    command: [ "python", "-m", "unittest", "discover", "-s", "backend/tests", "-t", "." ]